# Generated by Django 2.1.7 on 2022-01-10 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DmGroupsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(db_index=True, help_text='域名组', max_length=32, unique=True, verbose_name='域名组')),
            ],
            options={
                'db_table': 'resources_group',
            },
        ),
        migrations.CreateModel(
            name='DmModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, help_text='域名', max_length=32, unique=True, verbose_name='域名')),
                ('rewrite_url', models.CharField(help_text='跳转地址', max_length=32, verbose_name='跳转地址')),
                ('ct_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('group', models.ForeignKey(help_text='所属域名组', on_delete=django.db.models.deletion.DO_NOTHING, to='domain.DmGroupsModel', verbose_name='所属域名组')),
            ],
            options={
                'db_table': 'resources_domain',
                'ordering': ['id'],
            },
        ),
    ]
