# Generated by Django 2.1.8 on 2022-01-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmmodel',
            name='looks',
            field=models.PositiveIntegerField(default=0, verbose_name='访问量'),
        ),
    ]
