# Generated by Django 2.1.8 on 2022-01-13 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_auto_20220113_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmmodel',
            name='group',
            field=models.ForeignKey(help_text='所属域名组', on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='domain.DmGroupsModel', verbose_name='所属域名组'),
        ),
    ]
